### ISSUE TITLE
Issue with MathQuill Compound Unit Fix?

### ISSUE THREAD

**Issue by stebryan** [WeBWorK-for-Chemistry/Macros#5]
@limefrogyank 

- unit conversion problems with compound units giving an error when final answer is submitted
- Found so far in: setCH151_LearningChecks/module3-3a.pg, setCH151_UnitConversions/multiDimensionalAnalysis5.pg
- Only arises when final answer is placed in answer box.  Then this feedback appears:
![image](https://user-images.githubusercontent.com/121837027/232093487-0e2de599-ab98-47de-ba1e-3680a4ccf4b9.png)
- **students will encounter this within a week likely**.

**Comment by limefrogyank** [comment]
https://github.com/WeBWorK-for-Chemistry/Macros/blob/main/betterUnits.pl#L1015

This line and the denominator one had a bug.  Normally, all `$` in Perl prefix variable names and you can interpolate variables into strings this way.  I thought I had to escape the `$` with a backslash, but that was not necessary.  Removing the backslashes fixed it.

I also added another few tests in the InexactValueWithUnits test problem.

**Comment by limefrogyank** [comment]
Fixed with this commit:  https://github.com/WeBWorK-for-Chemistry/Macros/commit/ee1d675b634243e957342b12bedac2426308d7f1
